title_markdown = """
<div style="display: flex; justify-content: left; align-items: center; text-align: left; background: linear-gradient(45deg, rgba(195, 253, 245, 0.8), rgba(255, 0, 80, 0.3)); border-radius: 10px; box-shadow: 0 8px 16px 0 rgba(0,0,0,0.1);">  <a href="https://llava-vl.github.io/blog/2024-05-10-llava-next-stronger-llms/" style="margin-right: 20px; text-decoration: none; display: flex; align-items: center;">
    <img src="https://i.postimg.cc/JhT7zPj3/assistant-logo.png" alt="LLaVA-NeXT" style="max-width: 80px; height: auto; border-radius: 10px;">
  </a>
  <div>
    <h2 ><a href="https://llava-vl.github.io/blog/2024-05-10-llava-next-stronger-llms/">LLaVA OneVision: Multimodal Chat</a> </h2>
    <h5 style="margin: 0;"><a href="https://llavanext-video.lmms-lab.com/">Video Model</a> | <a href="https://github.com/LLaVA-VL/LLaVA-NeXT">Github</a> | <a href="https://huggingface.co/collections/lmms-lab/llava-next-6623288e2d61edba3ddbf5ff">Huggingface</a> | <a href="https://llava-vl.github.io/blog/2024-05-10-llava-next-stronger-llms/">Blog</a> | <a href="https://llava-vl.github.io">More</a></h5>
  </div>
</div>
"""

html_header = """
<style>
/* Existing Styles for Larger Screens */
.header-container {
  display: flex;
  justify-content: left;
  align-items: center;
  text-align: left;
  background: linear-gradient(45deg, rgba(195, 253, 245, 1), rgba(255, 0, 80, 0.3));
  border-radius: 10px;
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.1);
  padding: 10px 20px; /* Added padding */
}

.header-container img {
  max-width: 80px;
  height: auto;
  border-radius: 10px;
}

.header-container a {
  color: black; /* Ensure text color is always black */
  text-decoration: none;
}

/* Responsive adjustments for screens less than 768px wide */
@media (max-width: 768px) {
  .header-container {
    flex-direction: column;
    align-items: flex-start;
    padding: 10px 15px; /* Adjust padding for smaller screens */
  }

  .header-container img {
    max-width: 60px; /* Adjust image size for smaller screens */
  }

  .header-container h2, .header-container h5 {
  color: black; /* Ensure text color is always black */
  text-decoration: none;
    text-align: center; /* Center text on small screens */
    margin-top: 5px; /* Add top margin for better spacing after stacking */
  }

  .header-container h2 {
  color: black; /* Ensure text color is always black */
  text-decoration: none;
    font-size: 16px; /* Smaller font size for the title on mobile */
  }

  .header-container h5 {
  color: black; /* Ensure text color is always black */
  text-decoration: none;
    font-size: 12px; /* Smaller font size for the subtitle on mobile */
  }

  .header-container a {
  color: black; /* Ensure text color is always black */
  text-decoration: none;
  }
}
</style>

<div class="header-container">
  <a href="https://llava-vl.github.io/blog/2024-05-10-llava-next-stronger-llms/" style="margin-right: 20px; text-decoration: none; display: flex; align-items: center;">
    <img src="https://i.postimg.cc/JhT7zPj3/assistant-logo.png" alt="LLaVA-NeXT">
  </a>
  <div>
    <h2><a href="https://llava-vl.github.io/blog/2024-05-10-llava-next-stronger-llms/">LLaVA OneVision</a></h2>
    <h5><a href="https://github.com/LLaVA-VL/LLaVA-NeXT">Code</a> | <a href="https://huggingface.co/collections/lmms-lab/llava-onevision-66a259c3526e15166d6bba37">Checkpoints</a> | <a href="https://huggingface.co/datasets/lmms-lab/LLaVA-OneVision-Data">Data</a> | <a href="https://llava-vl.github.io/blog">LLaVA-NeXT Series Blog</a> | <a href="https://llava-onevision.lmms-lab.com/">OneVision-7B Demo</a></h5>
  </div>
</div>
"""

block_css = """
#buttons button {
    min-width: min(120px,100%);
}
"""

tos_markdown = """
## Terms of use
By using this service, users are required to agree to the following terms:
The service is a research preview intended for non-commercial use only. It only provides limited safety measures and may generate offensive content. It must not be used for any illegal, harmful, violent, racist, or sexual purposes. The service may collect user dialogue data for future research.

We deploy our model backend with SGLang. However, there could be congestion during the serving process, leading to delayed responses. If you encounter any issues with the webpage, kindly refresh it.
"""


learn_more_markdown = """
## License
The service is a research preview intended for non-commercial use only, subject to the model [License](https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md) of LLaMA, [Terms of Use](https://openai.com/policies/terms-of-use) of the data generated by OpenAI, and [Privacy Practices](https://chrome.google.com/webstore/detail/sharegpt-share-your-chatg/daiacboceoaocpibfodeljbdfacokfjb) of ShareGPT. Please contact us if you find any potential violation.
"""

bibtext = """
## Citation
```
@misc{li2024llavanext-strong,
    title={LLaVA-NeXT: Stronger LLMs Supercharge Multimodal Capabilities in the Wild},
    url={https://llava-vl.github.io/blog/2024-05-10-llava-next-stronger-llms/},
    author={Li, Bo and Zhang, Kaichen and Zhang, Hao and Guo, Dong and Zhang, Renrui and Li, Feng and Zhang, Yuanhan and Liu, Ziwei and Li, Chunyuan},
    month={May},
    year={2024}
}
```
"""

block_css = """

#buttons button {
    min-width: min(120px,100%);
}

"""
